# Enable OpenMP for Clang
message(STATUS "BigMac -> Setting OpenMP variables for ${CMAKE_CXX_COMPILER_ID}")
set(OpenMP_INCLUDE_PATH "/usr/local/include")
set(OpenMP_LIB_PATH "/usr/local/lib")
set(OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp -lomp")
set(OpenMP_CXX_LIB_NAMES "omp")
set(OpenMP_CXX_LIBRARIES "${OpenMP_LIB_PATH}/libomp.dylib")
include_directories(${OpenMP_INCLUDE_PATH})
link_directories(${OpenMP_LIB_PATH})
message(STATUS "        - OpenMP_INCLUDE_PATH ${OpenMP_INCLUDE_PATH}")
message(STATUS "        - OpenMP_LIB_PATH ${OpenMP_LIB_PATH}")
message(STATUS "        - OpenMP_CXX_FLAGS ${OpenMP_CXX_FLAGS}")
message(STATUS "        - OpenMP_CXX_LIB_NAMES ${OpenMP_CXX_LIB_NAMES}")
message(STATUS "        - OpenMP_CXX_LIBRARIES ${OpenMP_CXX_LIBRARIES}")

# Set FFTW flags for Clang
message(STATUS "BigMac -> Setting FFTW variables for ${CMAKE_CXX_COMPILER_ID}")
set(FFTW_OMP_FLAGS "-lomp")
set(FFTW_CXX_FLAGS "-Xpreprocessor -fopenmp")
message(STATUS "        - FFTW_OMP_FLAGS ${FFTW_OMP_FLAGS}")
message(STATUS "        - FFTW_CXX_FLAGS ${FFTW_CXX_FLAGS}")
